#! /bin/sh

chosen=$(printf " Config Files\n Bitwarden\n Calculator\n Void Packages" | dmenu -i -p ' ' )

case "$chosen" in
  " Config Files") $HOME/Others/Scripts/dmenu-files ;;
  " Bitwarden") $HOME/Others/Scripts/rofi-rbw ;;
  " Calculator") $HOME/Others/Scripts/rofi-calc ;;
  " Void Packages") $HOME/Others/Scripts/srcscript-dmenu ;;
  *) exit 1 ;;
esac
